# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'conntest.ui'
#
# Created: Tue Jan 12 22:59:13 2010
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_conntest(object):
    def setupUi(self, conntest):
        conntest.setObjectName("conntest")
        conntest.resize(714, 328)
        self.verticalLayout = QtGui.QVBoxLayout(conntest)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtGui.QLabel(conntest)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.txtHost = QtGui.QLineEdit(conntest)
        self.txtHost.setObjectName("txtHost")
        self.horizontalLayout_3.addWidget(self.txtHost)
        self.spnPort = QtGui.QSpinBox(conntest)
        self.spnPort.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spnPort.setMinimum(1)
        self.spnPort.setMaximum(655535)
        self.spnPort.setProperty("value", 10123)
        self.spnPort.setObjectName("spnPort")
        self.horizontalLayout_3.addWidget(self.spnPort)
        self.btnConnect = QtGui.QPushButton(conntest)
        self.btnConnect.setObjectName("btnConnect")
        self.horizontalLayout_3.addWidget(self.btnConnect)
        self.btnDisconnect = QtGui.QPushButton(conntest)
        self.btnDisconnect.setObjectName("btnDisconnect")
        self.horizontalLayout_3.addWidget(self.btnDisconnect)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.tabWidget = QtGui.QTabWidget(conntest)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidget = QtGui.QTableWidget(self.tab)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tableWidget2 = QtGui.QTableWidget(self.tab_2)
        self.tableWidget2.setObjectName("tableWidget2")
        self.tableWidget2.setColumnCount(2)
        self.tableWidget2.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget2.setHorizontalHeaderItem(1, item)
        self.verticalLayout_4.addWidget(self.tableWidget2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cmbCommand = QtGui.QComboBox(self.tab_2)
        self.cmbCommand.setObjectName("cmbCommand")
        self.cmbCommand.addItem("")
        self.cmbCommand.addItem("")
        self.cmbCommand.addItem("")
        self.horizontalLayout.addWidget(self.cmbCommand)
        self.spnID = QtGui.QSpinBox(self.tab_2)
        self.spnID.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spnID.setMinimum(100)
        self.spnID.setMaximum(999)
        self.spnID.setProperty("value", 100)
        self.spnID.setObjectName("spnID")
        self.horizontalLayout.addWidget(self.spnID)
        self.cmbObject = QtGui.QComboBox(self.tab_2)
        self.cmbObject.setObjectName("cmbObject")
        self.cmbObject.addItem("")
        self.cmbObject.addItem("")
        self.cmbObject.addItem("")
        self.horizontalLayout.addWidget(self.cmbObject)
        self.txtArg1 = QtGui.QLineEdit(self.tab_2)
        self.txtArg1.setObjectName("txtArg1")
        self.horizontalLayout.addWidget(self.txtArg1)
        self.txtArg2 = QtGui.QLineEdit(self.tab_2)
        self.txtArg2.setObjectName("txtArg2")
        self.horizontalLayout.addWidget(self.txtArg2)
        self.txtArg3 = QtGui.QLineEdit(self.tab_2)
        self.txtArg3.setObjectName("txtArg3")
        self.horizontalLayout.addWidget(self.txtArg3)
        self.btnSend = QtGui.QPushButton(self.tab_2)
        self.btnSend.setObjectName("btnSend")
        self.horizontalLayout.addWidget(self.btnSend)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(conntest)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(conntest)
        conntest.setTabOrder(self.txtHost, self.spnPort)
        conntest.setTabOrder(self.spnPort, self.btnConnect)
        conntest.setTabOrder(self.btnConnect, self.btnDisconnect)
        conntest.setTabOrder(self.btnDisconnect, self.tabWidget)
        conntest.setTabOrder(self.tabWidget, self.tableWidget2)
        conntest.setTabOrder(self.tableWidget2, self.cmbCommand)
        conntest.setTabOrder(self.cmbCommand, self.spnID)
        conntest.setTabOrder(self.spnID, self.cmbObject)
        conntest.setTabOrder(self.cmbObject, self.txtArg1)
        conntest.setTabOrder(self.txtArg1, self.txtArg2)
        conntest.setTabOrder(self.txtArg2, self.txtArg3)
        conntest.setTabOrder(self.txtArg3, self.btnSend)
        conntest.setTabOrder(self.btnSend, self.tableWidget)

    def retranslateUi(self, conntest):
        conntest.setWindowTitle(QtGui.QApplication.translate("conntest", "Connection Test", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("conntest", "Host:", None, QtGui.QApplication.UnicodeUTF8))
        self.txtHost.setText(QtGui.QApplication.translate("conntest", "127.0.0.1", None, QtGui.QApplication.UnicodeUTF8))
        self.spnPort.setPrefix(QtGui.QApplication.translate("conntest", ":", None, QtGui.QApplication.UnicodeUTF8))
        self.btnConnect.setText(QtGui.QApplication.translate("conntest", "Connect!", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDisconnect.setText(QtGui.QApplication.translate("conntest", "disconnect", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("conntest", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("conntest", "Object Name", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("conntest", "Related Help", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("conntest", "Object list", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget2.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("conntest", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget2.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("conntest", "Log", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbCommand.setItemText(0, QtGui.QApplication.translate("conntest", "!call@", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbCommand.setItemText(1, QtGui.QApplication.translate("conntest", "!help@", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbCommand.setItemText(2, QtGui.QApplication.translate("conntest", "!monitor@", None, QtGui.QApplication.UnicodeUTF8))
        self.spnID.setPrefix(QtGui.QApplication.translate("conntest", "m", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbObject.setItemText(0, QtGui.QApplication.translate("conntest", "fn:getFunctionList", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbObject.setItemText(1, QtGui.QApplication.translate("conntest", "fn:getEventList", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbObject.setItemText(2, QtGui.QApplication.translate("conntest", "ev:testEvent", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSend.setText(QtGui.QApplication.translate("conntest", "Send!", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("conntest", "Output Log", None, QtGui.QApplication.UnicodeUTF8))

