# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'navigator.ui'
#
# Created: Tue Jan 12 22:59:14 2010
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_navigator(object):
    def setupUi(self, navigator):
        navigator.setObjectName("navigator")
        navigator.resize(714, 566)
        self.tabWidget = QtGui.QTabWidget(navigator)
        self.tabWidget.setGeometry(QtCore.QRect(300, 360, 411, 191))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 200))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setContentsMargins(-1, -1, -1, 1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.textBrowser_2 = QtGui.QTextBrowser(self.tab)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.verticalLayout_6.addWidget(self.textBrowser_2)
        self.lineEdit = QtGui.QLineEdit(self.tab)
        self.lineEdit.setFrame(True)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_6.addWidget(self.lineEdit)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.plainTextEdit = QtGui.QPlainTextEdit(self.tab_2)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout_7.addWidget(self.plainTextEdit)
        self.tabWidget.addTab(self.tab_2, "")
        self.widget = QtGui.QWidget(navigator)
        self.widget.setGeometry(QtCore.QRect(10, 0, 276, 551))
        self.widget.setObjectName("widget")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.toolBox = QtGui.QToolBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setMaximumSize(QtCore.QSize(260, 16777215))
        self.toolBox.setObjectName("toolBox")
        self.toolBoxPage1 = QtGui.QWidget()
        self.toolBoxPage1.setEnabled(True)
        self.toolBoxPage1.setAutoFillBackground(False)
        self.toolBoxPage1.setObjectName("toolBoxPage1")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.toolBoxPage1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtGui.QLabel(self.toolBoxPage1)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.txtHost = QtGui.QLineEdit(self.toolBoxPage1)
        self.txtHost.setObjectName("txtHost")
        self.horizontalLayout_3.addWidget(self.txtHost)
        self.spnPort = QtGui.QSpinBox(self.toolBoxPage1)
        self.spnPort.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spnPort.setMinimum(1)
        self.spnPort.setMaximum(655535)
        self.spnPort.setProperty("value", 10123)
        self.spnPort.setObjectName("spnPort")
        self.horizontalLayout_3.addWidget(self.spnPort)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnConnect = QtGui.QPushButton(self.toolBoxPage1)
        self.btnConnect.setObjectName("btnConnect")
        self.horizontalLayout_2.addWidget(self.btnConnect)
        self.pushButton = QtGui.QPushButton(self.toolBoxPage1)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.lblStatus = QtGui.QLabel(self.toolBoxPage1)
        self.lblStatus.setObjectName("lblStatus")
        self.verticalLayout_2.addWidget(self.lblStatus)
        spacerItem = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.verticalLayout_2.addItem(spacerItem)
        self.toolBox.addItem(self.toolBoxPage1, "")
        self.toolBoxPage2 = QtGui.QWidget()
        self.toolBoxPage2.setObjectName("toolBoxPage2")
        self.verticalLayout = QtGui.QVBoxLayout(self.toolBoxPage2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget = QtGui.QListWidget(self.toolBoxPage2)
        self.listWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.listWidget.setAlternatingRowColors(True)
        self.listWidget.setObjectName("listWidget")
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        self.verticalLayout.addWidget(self.listWidget)
        self.toolBox.addItem(self.toolBoxPage2, "")
        self.page = QtGui.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.page)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.listWidget_2 = QtGui.QListWidget(self.page)
        self.listWidget_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.listWidget_2.setAlternatingRowColors(True)
        self.listWidget_2.setObjectName("listWidget_2")
        self.verticalLayout_3.addWidget(self.listWidget_2)
        self.toolBox.addItem(self.page, "")
        self.verticalLayout_5.addWidget(self.toolBox)
        self.groupBox = QtGui.QGroupBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.textBrowser = QtGui.QTextBrowser(self.groupBox)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_4.addWidget(self.textBrowser)
        self.verticalLayout_5.addWidget(self.groupBox)

        self.retranslateUi(navigator)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(navigator)

    def retranslateUi(self, navigator):
        navigator.setWindowTitle(QtGui.QApplication.translate("navigator", "Navigator", None, QtGui.QApplication.UnicodeUTF8))
        self.textBrowser_2.setHtml(QtGui.QApplication.translate("navigator", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'DejaVu Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">--- connection log ---</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("navigator", "ConnectionLog", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("navigator", "Python code editor", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBoxPage1.setAccessibleName(QtGui.QApplication.translate("navigator", "asd", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBoxPage1.setAccessibleDescription(QtGui.QApplication.translate("navigator", "asd", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("navigator", "Host:", None, QtGui.QApplication.UnicodeUTF8))
        self.txtHost.setText(QtGui.QApplication.translate("navigator", "127.0.0.1", None, QtGui.QApplication.UnicodeUTF8))
        self.spnPort.setPrefix(QtGui.QApplication.translate("navigator", ":", None, QtGui.QApplication.UnicodeUTF8))
        self.btnConnect.setText(QtGui.QApplication.translate("navigator", "Connect!", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("navigator", "Close Connection", None, QtGui.QApplication.UnicodeUTF8))
        self.lblStatus.setText(QtGui.QApplication.translate("navigator", "Current Status: Disconnected", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.toolBoxPage1), QtGui.QApplication.translate("navigator", "Connect to IRPC Server", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        self.listWidget.item(0).setText(QtGui.QApplication.translate("navigator", "getFunctionList", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(1).setText(QtGui.QApplication.translate("navigator", "getEventList", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.toolBox.setItemText(self.toolBox.indexOf(self.toolBoxPage2), QtGui.QApplication.translate("navigator", "Available Functions", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), QtGui.QApplication.translate("navigator", "Available Events", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("navigator", "Item Help", None, QtGui.QApplication.UnicodeUTF8))

